"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge, btn2Cls, btnCls, inputCls } from "./ui";
type Col = { id: string; slug: string; title: string; description: string | null; isPublished: boolean; sortOrder: number; featuredWorkId: string | null };
type P = { id: string; title: string; status: string };
export function CollectionsManager({ collections, poems, membership }: { collections: Col[]; poems: P[]; membership: Record<string, string[]> }) {
  const router = useRouter(); const [sel, setSel] = useState<Col | null>(collections[0] ?? null); const [creating, setCreating] = useState(false);
  const [form, setForm] = useState<{ title: string; description: string; isPublished: boolean; sortOrder: number; featuredWorkId: string; poemIds: string[] }>(() => sel ? { title: sel.title, description: sel.description ?? "", isPublished: sel.isPublished, sortOrder: sel.sortOrder, featuredWorkId: sel.featuredWorkId ?? "", poemIds: membership[sel.id] ?? [] } : { title: "", description: "", isPublished: true, sortOrder: 0, featuredWorkId: "", poemIds: [] });
  const [filter, setFilter] = useState(""); const [busy, setBusy] = useState(false); const [msg, setMsg] = useState<string | null>(null);
  const pick = (c: Col | null) => { setSel(c); setCreating(!c); setForm(c ? { title: c.title, description: c.description ?? "", isPublished: c.isPublished, sortOrder: c.sortOrder, featuredWorkId: c.featuredWorkId ?? "", poemIds: membership[c.id] ?? [] } : { title: "", description: "", isPublished: true, sortOrder: collections.length, featuredWorkId: "", poemIds: [] }); };
  const save = async () => { setBusy(true); const body = { ...form, featuredWorkId: form.featuredWorkId || null }; const r = await fetch(sel ? `/api/v1/admin/collections/${sel.id}` : "/api/v1/admin/collections", { method: sel ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setBusy(false); if (r.ok) { setMsg("Saved"); router.refresh(); } else setMsg((await r.json()).error?.message ?? "Failed"); };
  const del = async () => { if (!sel || !confirm(`Delete collection “${sel.title}”? Poems are not deleted.`)) return; await fetch(`/api/v1/admin/collections/${sel.id}`, { method: "DELETE" }); router.refresh(); pick(null); };
  const visible = poems.filter((p) => p.title.toLowerCase().includes(filter.toLowerCase()));
  return (<div className="grid gap-8 lg:grid-cols-[16rem_1fr]">
    <ul className="rounded border rule font-ui text-sm divide-y divide-[var(--rule)]">{collections.map((c) => <li key={c.id}><button type="button" onClick={() => pick(c)} className={`flex w-full items-center justify-between px-3 py-2 text-left hover:bg-paper-2 ${sel?.id === c.id ? "text-accent" : ""}`}>{c.title}<span className="text-ink-3 tabular-nums">{membership[c.id]?.length ?? 0}</span></button></li>)}<li><button type="button" onClick={() => pick(null)} className={`w-full px-3 py-2 text-left hover:bg-paper-2 ${creating ? "text-accent" : "text-ink-3"}`}>+ New collection</button></li></ul>
    <div className="space-y-4 font-ui text-sm">
      <div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="eyebrow">Title</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={inputCls} /></label><label className="block"><span className="eyebrow">Order</span><input type="number" value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: Number(e.target.value) })} className={inputCls} /></label></div>
      <label className="block"><span className="eyebrow">Description</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} rows={2} className={inputCls} /></label>
      <div className="flex flex-wrap gap-6"><label className="flex items-center gap-2"><input type="checkbox" checked={form.isPublished} onChange={(e) => setForm({ ...form, isPublished: e.target.checked })} />Published</label><label className="flex items-center gap-2">Featured poem<select value={form.featuredWorkId} onChange={(e) => setForm({ ...form, featuredWorkId: e.target.value })} className={inputCls + " w-auto"}><option value="">(first in list)</option>{poems.filter((p) => form.poemIds.includes(p.id)).map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div>
      <div><div className="flex items-center justify-between"><span className="eyebrow">Poems in this collection ({form.poemIds.length})</span><input placeholder="Filter…" value={filter} onChange={(e) => setFilter(e.target.value)} className={inputCls + " w-48"} /></div>
        <ul className="mt-2 max-h-[26rem] overflow-y-auto rounded border rule p-2 columns-1 md:columns-2">{visible.map((p) => <li key={p.id}><label className="flex items-center gap-2 py-0.5"><input type="checkbox" checked={form.poemIds.includes(p.id)} onChange={(e) => setForm({ ...form, poemIds: e.target.checked ? [...form.poemIds, p.id] : form.poemIds.filter((x) => x !== p.id) })} /><span className="truncate">{p.title}</span>{p.status !== "PUBLISHED" && <Badge tone="warn">{p.status}</Badge>}</label></li>)}</ul></div>
      <div className="flex items-center gap-3"><button type="button" onClick={save} disabled={busy || !form.title} className={btnCls}>{sel ? "Save collection" : "Create collection"}</button>{sel && <button type="button" onClick={del} className={btn2Cls}>Delete</button>}<span className="text-ink-3" aria-live="polite">{msg}</span></div>
    </div>
  </div>);
}
