"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { btn2Cls, btnCls, inputCls } from "./ui";
const SOURCES = [["MY_POETIC_SIDE", "My Poetic Side"], ["POETRY_COM", "Poetry.com"], ["ANTHOLOGY", "Anthology PDF"], ["PDF", "Other PDF"], ["HTML", "HTML"], ["MARKDOWN", "Markdown"], ["TXT", "Plain text"], ["CSV", "CSV"], ["JSON", "JSON"], ["MANUAL", "Manual"]];
export function ImportForm() {
  const router = useRouter(); const [tab, setTab] = useState<"url" | "file" | "paste">("url"); const [busy, setBusy] = useState(false); const [err, setErr] = useState<string | null>(null);
  const [url, setUrl] = useState("https://mypoeticside.com/user-51801"); const [source, setSource] = useState("MY_POETIC_SIDE"); const [text, setText] = useState(""); const [label, setLabel] = useState("Pasted poems"); const [pasteUrl, setPasteUrl] = useState("");
  const done = async (r: Response) => { const j = await r.json(); setBusy(false); if (!r.ok) { setErr(j.error?.message ?? "Import failed"); return; } router.push(`/admin/import/${j.data.jobId}`); };
  const byUrl = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setErr(null); done(await fetch("/api/v1/admin/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url, source }) })); };
  const byFile = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setBusy(true); setErr(null); const fd = new FormData(e.currentTarget); done(await fetch("/api/v1/admin/import", { method: "POST", body: fd })); };
  const byPaste = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setErr(null); done(await fetch("/api/v1/admin/import", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text, source, label, url: pasteUrl || undefined }) })); };
  return (<div className="rounded border rule p-5 font-ui text-sm">
    <div className="mb-4 flex gap-2">{(["url", "file", "paste"] as const).map((t) => <button key={t} type="button" onClick={() => setTab(t)} className={`rounded px-3 py-1 ${tab === t ? "bg-paper-2 text-accent" : "text-ink-3"}`}>{{ url: "From URL", file: "Upload file", paste: "Paste text" }[t]}</button>)}</div>
    {tab === "url" && (<form onSubmit={byUrl} className="space-y-3"><p className="text-ink-2">Paste the author&apos;s profile URL or a single poem URL. Only mypoeticside.com and poetry.com are fetched, politely and with an identifiable user agent. If the site refuses automated access, you&apos;ll be asked to upload a saved HTML page instead.</p><div className="flex flex-wrap gap-2"><input value={url} onChange={(e) => setUrl(e.target.value)} className={inputCls + " flex-1 min-w-[16rem]"} type="url" required /><select value={source} onChange={(e) => setSource(e.target.value)} className={inputCls + " w-auto"}>{SOURCES.slice(0, 2).concat([["HTML", "Other HTML page"]]).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><button disabled={busy} className={btnCls}>{busy ? "Fetching… (may take a few minutes)" : "Fetch & preview"}</button></div></form>)}
    {tab === "file" && (<form onSubmit={byFile} className="space-y-3"><p className="text-ink-2">PDF (e.g. the My Poetic Side anthology), saved HTML pages, Markdown/TXT (poems separated by <code>---</code>), CSV (<code>title,body,date,url,tags</code>) or JSON (<code>[{'{'}title, body, date, url, tags{'}'}]</code>). Max 25 MB.</p><div className="flex flex-wrap gap-2 items-center"><input name="file" type="file" required accept=".pdf,.html,.htm,.txt,.md,.csv,.json" className="text-ink-2" /><select name="source" defaultValue="ANTHOLOGY" className={inputCls + " w-auto"}>{SOURCES.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><input name="url" placeholder="Original URL (provenance, optional)" className={inputCls + " w-72"} /><button disabled={busy} className={btnCls}>{busy ? "Parsing…" : "Upload & preview"}</button></div></form>)}
    {tab === "paste" && (<form onSubmit={byPaste} className="space-y-3"><p className="text-ink-2">First line is the title; separate poems with a line containing <code>---</code>. Add <code>Date: 2024-09-02</code> on its own line to record a date. Line breaks are kept exactly as pasted.</p><textarea value={text} onChange={(e) => setText(e.target.value)} rows={12} className={inputCls + " font-body text-base"} required placeholder={"The Day I Left\nDate: 2026-07-24\n\nNo one noticed\nthe exact moment\n…\n---\nNext poem title\n…"} /><div className="flex flex-wrap gap-2"><input value={label} onChange={(e) => setLabel(e.target.value)} className={inputCls + " w-56"} placeholder="Label" /><input value={pasteUrl} onChange={(e) => setPasteUrl(e.target.value)} className={inputCls + " w-72"} placeholder="Original URL (optional)" type="url" /><select value={source} onChange={(e) => setSource(e.target.value)} className={inputCls + " w-auto"}>{SOURCES.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><button disabled={busy} className={btnCls}>Preview</button></div></form>)}
    {err && <p role="alert" className="mt-3 text-red-700">{err}</p>}
    <p className="mt-4 text-xs text-ink-3">Nothing is written to the archive until you approve the preview. Existing poems are never overwritten silently. <a className={btn2Cls + " ml-2 px-2 py-0.5 text-xs"} href="/api/v1/admin/import" target="_blank">API</a></p>
  </div>);
}
