import Link from "next/link";
import { getDashboardStats } from "@/application/analytics/analytics-service";
import { PageTitle, Stat, Table } from "@/components/admin/ui";
import { languageLabel } from "@/domain/poem/language";
export default async function Analytics() {
  const s = await getDashboardStats(); const maxY = Math.max(1, ...s.byYear.map((y) => y.count)); const maxM = Math.max(1, ...s.byMonth.map((m) => m.count)); const maxV = Math.max(1, ...s.viewsByDay.map((v) => v.views));
  const completion = s.completion.views ? Math.round((s.completion.completions / s.completion.views) * 100) : 0;
  return (<>
    <PageTitle eyebrow="Private" title="Poetry stats" />
    <dl className="grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-6"><Stat label="Total poems" value={s.totals.total} /><Stat label="Published" value={s.totals.published} /><Stat label="Drafts" value={s.totals.drafts} sub={`${s.totals.review} in review`} /><Stat label="Words" value={s.totals.words.toLocaleString()} /><Stat label="Characters" value={s.totals.chars.toLocaleString()} /><Stat label="Languages" value={s.totals.languages} sub={s.byLanguage.map((l) => `${languageLabel(l.language)} ${l.count}`).join(" · ")} /><Stat label="Collections" value={s.totals.collections} /><Stat label="Tags" value={s.totals.tags} /><Stat label="Views (all time)" value={s.completion.views.toLocaleString()} /><Stat label="Reading completion" value={`${completion}%`} sub={`${s.completion.completions.toLocaleString()} finished`} /></dl>
    <div className="mt-10 grid gap-10 lg:grid-cols-2">
      <section><h2 className="eyebrow mb-3">Poems by year</h2><ul className="space-y-1.5 font-ui text-xs">{s.byYear.map((y) => <li key={y.year} className="grid grid-cols-[3rem_1fr_2rem] items-center gap-2"><span>{y.year}</span><span className="h-3 rounded-sm bg-accent/80" style={{ width: `${(y.count / maxY) * 100}%` }} /><span className="tabular-nums text-ink-3">{y.count}</span></li>)}</ul></section>
      <section><h2 className="eyebrow mb-3">Poems by month</h2><div className="flex h-32 items-end gap-[2px]" role="img" aria-label="Poems per month">{s.byMonth.map((m) => <span key={m.month} title={`${m.month}: ${m.count}`} className="flex-1 rounded-t-sm bg-accent/70" style={{ height: `${(m.count / maxM) * 100}%` }} />)}</div><p className="mt-1 flex justify-between font-ui text-[10px] text-ink-3"><span>{s.byMonth[0]?.month}</span><span>{s.byMonth.at(-1)?.month}</span></p></section>
      <section><h2 className="eyebrow mb-3">Views, last 30 days</h2>{s.viewsByDay.length === 0 ? <p className="font-ui text-xs text-ink-3">No views recorded yet.</p> : <div className="flex h-24 items-end gap-[2px]">{s.viewsByDay.map((v) => <span key={v.day} title={`${v.day}: ${v.views}`} className="flex-1 rounded-t-sm bg-ink/60" style={{ height: `${(v.views / maxV) * 100}%` }} />)}</div>}</section>
      <section><h2 className="eyebrow mb-3">Popular themes</h2><ul className="flex flex-wrap gap-2 font-ui text-xs">{s.themes.map((t) => <li key={t.slug} className="rounded-full border rule px-3 py-1">{t.name} <span className="text-ink-3">{t.count}</span></li>)}{s.themes.length === 0 && <li className="text-ink-3">No tags applied yet.</li>}</ul></section>
      <section><h2 className="eyebrow mb-3">Most read</h2><Table head={["Poem", "Views", "Finished"]}>{s.mostRead.map((p) => <tr key={p.id}><td><Link href={`/admin/poems/${p.id}`} className="link">{p.title}</Link></td><td className="tabular-nums">{p.views}</td><td className="tabular-nums">{p.completions}</td></tr>)}{s.mostRead.length === 0 && <tr><td colSpan={3} className="text-ink-3">—</td></tr>}</Table></section>
      <section><h2 className="eyebrow mb-3">Most favourited &amp; shared</h2><Table head={["Poem", "Favourites"]}>{s.mostFavorited.map((p) => <tr key={p.id}><td>{p.title}</td><td className="tabular-nums">{p.count}</td></tr>)}{s.mostFavorited.length === 0 && <tr><td colSpan={2} className="text-ink-3">—</td></tr>}</Table><div className="mt-3"><Table head={["Poem", "Shares"]}>{s.mostShared.map((p) => <tr key={p.id}><td>{p.title}</td><td className="tabular-nums">{p.count}</td></tr>)}{s.mostShared.length === 0 && <tr><td colSpan={2} className="text-ink-3">—</td></tr>}</Table></div></section>
      <section><h2 className="eyebrow mb-3">Search queries</h2><Table head={["Query", "Count", "Avg results"]}>{s.searches.map((q) => <tr key={q.query}><td>{q.query}</td><td className="tabular-nums">{q.count}</td><td className="tabular-nums">{q.avgResults}</td></tr>)}{s.searches.length === 0 && <tr><td colSpan={3} className="text-ink-3">—</td></tr>}</Table></section>
      <section><h2 className="eyebrow mb-3">Collections</h2><Table head={["Collection", "Poems"]}>{s.collections.map((c) => <tr key={c.slug}><td>{c.title}</td><td className="tabular-nums">{c.count}</td></tr>)}</Table></section>
    </div>
    <p className="mt-10 font-ui text-xs text-ink-3">All counters are anonymous daily aggregates. No visitor identifiers are stored.</p>
  </>);
}
